### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by JagaRamesh** [mnaithan/intro-data-capstone-biodiversity#1]
Overall, Excellent job explaining the analysis and the outcome in the document.

The powerpoint slides are sequenced very well. There is a lot of text in the slides. I would recommend to use one part of the slide for "findings" and the other part for "picture / plot " instead of having only the text in the slides. 

The matplotlib plots are neat with proper title, xlabel and ylabel defined.

The analysis and conclusion for “Endangerment of Species” and “Foot & Mouth disease for Sheep  in Parks“ are accurate. 

Great Job! KEEP IT UP!!

**Comment by mnaithan** [comment]
Thanks for the feedback JagaRamesh, will work on the points you mentioned, just wondering when I am going to get Codecademy Certificate ..?

Regards

Mayank

**Comment by JagaRamesh** [comment]
Check this article . Looks like you will receive it within 4 weeks.
https://help.codecademy.com/hc/en-us/articles/360000386153-When-will-I-receive-my-credential-for-completing-a-Pro-Intensive-

**Comment by JagaRamesh** [comment]
Congratulations in completing the course!!

**Comment by mnaithan** [comment]
Thank you very much ..!
